name: Build Samples
on:
  push:
    branches:
      - 2.0.x
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build-samples:
    name: Build Samples
    if: ${{ github.repository == 'spring-projects/spring-ws-samples' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: 'maven'
      - name: Build
        run: ./mvnw --no-transfer-progress --batch-mode --update-snapshots verify
      - name: Send notification
        uses: ./.github/actions/send-notification
        if: always()
        with:
          webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
          run-name: ${{ format('Spring WS Samples | {0} | {1}', github.ref_name, matrix.runner.name) }}
